
name: CI
on:
  push:
    branches: [master, main]
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
        command:
          - "test"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
      - run: sbt ${{ matrix.command }}
